[[redirects]]
  from = "/2013*"
  to = "https://archive-201x.codeursenseine.com/2013/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2014*"
  to = "https://archive-201x.codeursenseine.com/2014/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2015*"
  to = "https://archive-201x.codeursenseine.com/2015/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2016*"
  to = "https://archive-201x.codeursenseine.com/2016/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2017*"
  to = "https://archive-201x.codeursenseine.com/2017/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2018*"
  to = "https://archive-201x.codeursenseine.com/2018/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2019*"
  to = "https://archive-201x.codeursenseine.com/2019/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"
